const date = new Date();
const name = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const dummyarrr = [
  {
    date: new Date(),
    title: "Best practice",
    instructor: "Usama",
    certified: "Google Certified Flutter Developer",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best practice",
    instructor: "Saad Khan",
    certified: "Google Certified Flutter Developer",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best practice",
    instructor: "Umar Faddi",
    certified: "Google Certified Flutter Developer",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Web Development for Beginer",
    instructor: "Sunil Bhai",
    certified: "Google Certified Flutter Developer",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best practice",
    instructor: "Riayz Ahmed",
    certified: "Google Certified Flutter Developer",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
];
export default dummyarrr;
